# Generated by Django 4.1.1 on 2022-10-03 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.TextField()),
                ('response_status', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('twitter_session_id', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('oauth_token', models.CharField(default=None, max_length=100)),
                ('oauth_verifier', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserFavouriteAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourited_id', models.CharField(max_length=64)),
                ('twitter_session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.auth')),
            ],
        ),
    ]
