# Generated by Django 4.1.1 on 2022-09-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.TextField()),
                ('responseStatus', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('request_token', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('request_secret', models.CharField(max_length=100)),
            ],
        ),
    ]
