# Generated by Django 4.1.1 on 2022-09-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Authenticated",
            fields=[
                (
                    "access_token",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("email", models.CharField(max_length=64)),
                ("account_id", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="UserFavouriteAccounts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.CharField(max_length=64)),
                ("favourited_id", models.CharField(max_length=64)),
            ],
        ),
    ]
